---
# Configure OCP4 HAProxy Load balancer on Helper Node
- hosts: all
  vars_files:
    - ../vars/main.yml
  handlers:
  - import_tasks: ../handlers/main.yml

  tasks:
  - name: Install HaProxy packages
    ansible.builtin.yum:
      name:
        - haproxy
      state: latest

  - name: Set haproxy_connect_any  flag on and keep it persistent across reboots
    seboolean:
      name: haproxy_connect_any 
      state: true
      persistent: true

  - name: Move /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
    shell: mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default

  - name: Write out haproxy config file
    ansible.builtin.template:
      src: ../templates/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify:
      - restart haproxy

  #- name: Configure SElinux for HAProxy to use the custom ports configured
  #  command: sudo semanage port  -a 6443 -t http_port_t -p tcp
  #  #; sudo semanage port  -a 22623 -t http_port_t -p tcp; sudo semanage port -a 32700 -t http_port_t -p tcp
  - name: Configure SElinux for HAProxy to use the custom ports configured
    shell:  sudo semanage port  -a 22623 -t http_port_t -p tcp; sudo semanage port  -a 22623 -t http_port_t -p tcp; sudo semanage port -a 32700 -t http_port_t -p tcp
